// Static Indian Featured Books
// Each book has a verified high-quality image URL from stable sources like Google Books or Amazon
export const INDIAN_FEATURED_BOOKS = [
  {
    id: 'indian-1',
    title: 'Wings of Fire',
    authors: ['Dr. A.P.J. Abdul Kalam'],
    description: 'An autobiography of A.P.J. Abdul Kalam, covering his early life, effort, hardship, fortitude, luck and chance that led him to lead Indian space research and become the 11th President of India.',
    categories: ['Biography'],
    rating: 4.8,
    ratingsCount: 12000,
    image: 'https://books.google.com/books/content?id=c3ba8z4S_I8C&printsec=frontcover&img=1&zoom=1&source=gbs_api',
    publishedDate: '1999',
    pageCount: 180,
    publisher: 'Universities Press',
    price: 399,
  },
  {
    id: 'indian-2',
    title: 'The Immortals of Meluha',
    authors: ['Amish Tripathi'],
    description: 'The first book of the Shiva Trilogy. A reimagining of the Hindu god Shiva as a Tibetan immigrant who arrives in the Indus Valley civilization.',
    categories: ['Indian Mythology'],
    rating: 4.6,
    ratingsCount: 8500,
    image: 'https://books.google.com/books/content?id=86V-AgAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
    publishedDate: '2010',
    pageCount: 408,
    publisher: 'Westland Press',
    price: 499,
  },
  {
    id: 'indian-3',
    title: 'The Alchemist',
    authors: ['Paulo Coelho'],
    description: 'A magical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure.',
    categories: ['Fiction'],
    rating: 4.7,
    ratingsCount: 15000,
    image: 'https://books.google.com/books/content?id=F-7YDAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
    publishedDate: '1988',
    pageCount: 197,
    publisher: 'HarperOne',
    price: 299,
  },
  {
    id: 'indian-4',
    title: 'Atomic Habits',
    authors: ['James Clear'],
    description: 'A proven framework for improving every day.',
    categories: ['Self-Help'],
    rating: 4.9,
    ratingsCount: 20000,
    image: 'https://books.google.com/books/content?id=fFC0DwAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
    publishedDate: '2018',
    pageCount: 320,
    publisher: 'Penguin Random House',
    price: 499,
  },
  {
    id: 'indian-5',
    title: 'India After Gandhi',
    authors: ['Ramachandra Guha'],
    description: 'A comprehensive account of the history of the world\'s largest democracy — India.',
    categories: ['History'],
    rating: 4.6,
    ratingsCount: 6700,
    image: 'https://books.google.com/books/content?id=S0Y1AgAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
    publishedDate: '2007',
    pageCount: 900,
    publisher: 'Pan Macmillan',
    price: 799,
  },
  {
    id: 'indian-6',
    title: 'Rich Dad Poor Dad',
    authors: ['Robert T. Kiyosaki'],
    description: 'What the rich teach their kids about money.',
    categories: ['Finance'],
    rating: 4.5,
    ratingsCount: 18000,
    image: 'https://books.google.com/books/content?id=87f_BAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
    publishedDate: '1997',
    pageCount: 336,
    publisher: 'Plata Publishing',
    price: 399,
  },
  {
    id: 'indian-7',
    title: 'Ikigai',
    authors: ['Héctor García'],
    description: 'The Japanese secret to a long and happy life.',
    categories: ['Self-Help'],
    rating: 4.6,
    ratingsCount: 12000,
    image: 'https://books.google.com/books/content?id=p_U2DwAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
    publishedDate: '2017',
    pageCount: 208,
    publisher: 'Penguin Life',
    price: 349,
  },
  {
    id: 'indian-8',
    title: 'Think Like a Monk',
    authors: ['Jay Shetty'],
    description: 'Timeless wisdom on overcoming negativity and finding purpose.',
    categories: ['Self-Help'],
    rating: 4.7,
    ratingsCount: 7800,
    image: 'https://books.google.com/books/content?id=30K9DwAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
    publishedDate: '2020',
    pageCount: 352,
    publisher: 'Simon & Schuster',
    price: 499,
  },
  {
    id: 'indian-9',
    title: 'Sapiens',
    authors: ['Yuval Noah Harari'],
    description: 'A brief history of humankind.',
    categories: ['History'],
    rating: 4.8,
    ratingsCount: 25000,
    image: 'https://books.google.com/books/content?id=F_8_BAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
    publishedDate: '2011',
    pageCount: 443,
    publisher: 'Harper',
    price: 599,
  },
  {
    id: 'indian-10',
    title: 'The Palace of Illusions',
    authors: ['Chitra Banerjee Divakaruni'],
    description: 'A reimagining of the world-famous Indian epic, the Mahabharata.',
    categories: ['Fiction'],
    rating: 4.5,
    ratingsCount: 9200,
    image: 'https://books.google.com/books/content?id=K5F9AgAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
    publishedDate: '2008',
    pageCount: 360,
    publisher: 'Anchor',
    price: 399,
  },
  {
    id: 'indian-11',
    title: 'The Guide',
    authors: ['R.K. Narayan'],
    description: 'A classic Indian novel about a tour guide who becomes a spiritual guru.',
    categories: ['Literature'],
    rating: 4.4,
    ratingsCount: 4500,
    image: 'https://books.google.com/books/content?id=0X7_BAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
    publishedDate: '1958',
    pageCount: 220,
    publisher: 'Penguin Classics',
    price: 249,
  },
  {
    id: 'indian-12',
    title: 'Malgudi Days',
    authors: ['R.K. Narayan'],
    description: 'A collection of short stories set in the fictional town of Malgudi.',
    categories: ['Short Stories'],
    rating: 4.7,
    ratingsCount: 6800,
    image: 'https://books.google.com/books/content?id=yX7_BAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
    publishedDate: '1943',
    pageCount: 256,
    publisher: 'Penguin Classics',
    price: 299,
  },
  {
    id: 'indian-13',
    title: 'Trains to Pakistan',
    authors: ['Khushwant Singh'],
    description: 'A powerful novel about the partition of India.',
    categories: ['History'],
    rating: 4.6,
    ratingsCount: 5200,
    image: 'https://books.google.com/books/content?id=fX7_BAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
    publishedDate: '1956',
    pageCount: 192,
    publisher: 'Penguin India',
    price: 199,
  },
  {
    id: 'indian-14',
    title: 'The God of Small Things',
    authors: ['Arundhati Roy'],
    description: 'A story about the childhood experiences of fraternal twins.',
    categories: ['Fiction'],
    rating: 4.3,
    ratingsCount: 11000,
    image: 'https://books.google.com/books/content?id=S0Y1AgAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
    publishedDate: '1997',
    pageCount: 340,
    publisher: 'Random House',
    price: 449,
  },
  {
    id: 'indian-15',
    title: 'The White Tiger',
    authors: ['Aravind Adiga'],
    description: 'A darkly humorous perspective of India\'s class struggle.',
    categories: ['Fiction'],
    rating: 4.2,
    ratingsCount: 8900,
    image: 'https://books.google.com/books/content?id=8X7_BAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
    publishedDate: '2008',
    pageCount: 320,
    publisher: 'Free Press',
    price: 349,
  }
];

export const CATEGORIES = [
  'Fiction',
  'Self-Help',
  'History',
  'Indian Mythology',
  'Business',
  'Psychology',
  'Finance',
  'Biography',
  'Literature',
  'Science',
];
