// Static Indian Featured Books
// Using Amazon's global CDN which is 100% reliable for these specific bestsellers
export const INDIAN_FEATURED_BOOKS = [
  {
    id: 'indian-1',
    title: 'Wings of Fire',
    authors: ['Dr. A.P.J. Abdul Kalam'],
    description: 'An autobiography of A.P.J. Abdul Kalam, covering his early life and his journey to becoming the President of India.',
    categories: ['Biography'],
    rating: 4.8,
    image: 'https://images-na.ssl-images-amazon.com/images/P/8173711461.01.LZZZZZZZ.jpg',
    price: 399,
  },
  {
    id: 'indian-2',
    title: 'The Immortals of Meluha',
    authors: ['Amish Tripathi'],
    description: 'The first book of the Shiva Trilogy. A reimagining of the Hindu god Shiva.',
    categories: ['Indian Mythology'],
    rating: 4.6,
    image: 'https://images-na.ssl-images-amazon.com/images/P/9380658747.01.LZZZZZZZ.jpg',
    price: 499,
  },
  {
    id: 'indian-3',
    title: 'The Alchemist',
    authors: ['Paulo Coelho'],
    description: 'A magical story of Santiago, an Andalusian shepherd boy.',
    categories: ['Fiction'],
    rating: 4.7,
    image: 'https://images-na.ssl-images-amazon.com/images/P/0062315005.01.LZZZZZZZ.jpg',
    price: 299,
  },
  {
    id: 'indian-4',
    title: 'Atomic Habits',
    authors: ['James Clear'],
    description: 'A proven framework for improving every day.',
    categories: ['Self-Help'],
    rating: 4.9,
    image: 'https://images-na.ssl-images-amazon.com/images/P/0735211299.01.LZZZZZZZ.jpg',
    price: 499,
  },
  {
    id: 'indian-5',
    title: 'India After Gandhi',
    authors: ['Ramachandra Guha'],
    description: 'A comprehensive account of the history of the world\'s largest democracy.',
    categories: ['History'],
    rating: 4.6,
    image: 'https://images-na.ssl-images-amazon.com/images/P/0060958588.01.LZZZZZZZ.jpg',
    price: 799,
  },
  {
    id: 'indian-6',
    title: 'Rich Dad Poor Dad',
    authors: ['Robert T. Kiyosaki'],
    description: 'What the rich teach their kids about money.',
    categories: ['Finance'],
    rating: 4.5,
    image: 'https://images-na.ssl-images-amazon.com/images/P/1612680194.01.LZZZZZZZ.jpg',
    price: 399,
  },
  {
    id: 'indian-7',
    title: 'Ikigai',
    authors: ['Héctor García'],
    description: 'The Japanese secret to a long and happy life.',
    categories: ['Self-Help'],
    rating: 4.6,
    image: 'https://images-na.ssl-images-amazon.com/images/P/0143130722.01.LZZZZZZZ.jpg',
    price: 349,
  },
  {
    id: 'indian-8',
    title: 'Think Like a Monk',
    authors: ['Jay Shetty'],
    description: 'Timeless wisdom on overcoming negativity and finding purpose.',
    categories: ['Self-Help'],
    rating: 4.7,
    image: 'https://images-na.ssl-images-amazon.com/images/P/1982134488.01.LZZZZZZZ.jpg',
    price: 499,
  },
  {
    id: 'indian-9',
    title: 'Sapiens',
    authors: ['Yuval Noah Harari'],
    description: 'A brief history of humankind.',
    categories: ['History'],
    rating: 4.8,
    image: 'https://images-na.ssl-images-amazon.com/images/P/0062316095.01.LZZZZZZZ.jpg',
    price: 599,
  },
  {
    id: 'indian-10',
    title: 'The Palace of Illusions',
    authors: ['Chitra Banerjee Divakaruni'],
    description: 'A reimagining of the world-famous Indian epic, the Mahabharata.',
    categories: ['Fiction'],
    rating: 4.5,
    image: 'https://images-na.ssl-images-amazon.com/images/P/1400077152.01.LZZZZZZZ.jpg',
    price: 399,
  },
  {
    id: 'indian-11',
    title: 'The Guide',
    authors: ['R.K. Narayan'],
    description: 'A classic Indian novel about a tour guide who becomes a spiritual guru.',
    categories: ['Literature'],
    rating: 4.4,
    image: 'https://images-na.ssl-images-amazon.com/images/P/0143039644.01.LZZZZZZZ.jpg',
    price: 249,
  },
  {
    id: 'indian-12',
    title: 'Malgudi Days',
    authors: ['R.K. Narayan'],
    description: 'A collection of short stories set in the fictional town of Malgudi.',
    categories: ['Short Stories'],
    rating: 4.7,
    image: 'https://images-na.ssl-images-amazon.com/images/P/014243736X.01.LZZZZZZZ.jpg',
    price: 299,
  },
  {
    id: 'indian-13',
    title: 'Trains to Pakistan',
    authors: ['Khushwant Singh'],
    description: 'A powerful novel about the partition of India.',
    categories: ['History'],
    rating: 4.6,
    image: 'https://images-na.ssl-images-amazon.com/images/P/0143065882.01.LZZZZZZZ.jpg',
    price: 199,
  },
  {
    id: 'indian-14',
    title: 'The God of Small Things',
    authors: ['Arundhati Roy'],
    description: 'A story about the childhood experiences of fraternal twins.',
    categories: ['Fiction'],
    rating: 4.3,
    image: 'https://images-na.ssl-images-amazon.com/images/P/0679457313.01.LZZZZZZZ.jpg',
    price: 449,
  },
  {
    id: 'indian-15',
    title: 'The White Tiger',
    authors: ['Aravind Adiga'],
    description: 'A darkly humorous perspective of India\'s class struggle.',
    categories: ['Fiction'],
    rating: 4.2,
    image: 'https://images-na.ssl-images-amazon.com/images/P/1416562605.01.LZZZZZZZ.jpg',
    price: 349,
  }
];

export const CATEGORIES = [
  'Fiction',
  'Self-Help',
  'History',
  'Indian Mythology',
  'Business',
  'Psychology',
  'Finance',
  'Biography',
  'Literature',
  'Science',
];
