// Static Indian Featured Books
export const INDIAN_FEATURED_BOOKS = [
  {
    id: 'indian-1',
    title: 'Wings of Fire',
    authors: ['Dr. A.P.J. Abdul Kalam'],
    description: 'An autobiography of A.P.J. Abdul Kalam, covering his early life, effort, hardship, fortitude, luck and chance that led him to lead Indian space research and become the 11th President of India.',
    categories: ['Biography'],
    rating: 4.8,
    ratingsCount: 12000,
    image: 'https://covers.openlibrary.org/b/isbn/9788173711466-L.jpg',
    publishedDate: '1999',
    pageCount: 180,
    publisher: 'Universities Press',
    price: 399,
    previewLink: '#',
  },
  {
    id: 'indian-2',
    title: 'The Immortals of Meluha',
    authors: ['Amish Tripathi'],
    description: 'The first book of the Shiva Trilogy. A reimagining of the Hindu god Shiva as a Tibetan immigrant who arrives in the Indus Valley civilization and discovers his destiny.',
    categories: ['Indian Mythology'],
    rating: 4.6,
    ratingsCount: 8500,
    image: 'https://covers.openlibrary.org/b/isbn/9789380658742-L.jpg',
    publishedDate: '2010',
    pageCount: 408,
    publisher: 'Westland Press',
    price: 499,
    previewLink: '#',
  },
  {
    id: 'indian-3',
    title: 'The Alchemist',
    authors: ['Paulo Coelho'],
    description: 'A magical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure.',
    categories: ['Fiction'],
    rating: 4.7,
    ratingsCount: 15000,
    image: 'https://covers.openlibrary.org/b/isbn/9780062315007-L.jpg',
    publishedDate: '1988',
    pageCount: 197,
    publisher: 'HarperOne',
    price: 299,
    previewLink: '#',
  },
  {
    id: 'indian-4',
    title: 'Atomic Habits',
    authors: ['James Clear'],
    description: 'A proven framework for improving every day.',
    categories: ['Self-Help'],
    rating: 4.9,
    ratingsCount: 20000,
    image: 'https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg',
    publishedDate: '2018',
    pageCount: 320,
    publisher: 'Penguin Random House',
    price: 499,
    previewLink: '#',
  },
  {
    id: 'indian-5',
    title: 'India After Gandhi',
    authors: ['Ramachandra Guha'],
    description: 'A comprehensive account of the history of the world\'s largest democracy — India.',
    categories: ['History'],
    rating: 4.6,
    ratingsCount: 6700,
    image: 'https://covers.openlibrary.org/b/isbn/9780330396110-L.jpg',
    publishedDate: '2007',
    pageCount: 900,
    publisher: 'Pan Macmillan',
    price: 799,
    previewLink: '#',
  },
  {
    id: 'indian-6',
    title: 'Rich Dad Poor Dad',
    authors: ['Robert T. Kiyosaki'],
    description: 'What the rich teach their kids about money.',
    categories: ['Finance'],
    rating: 4.5,
    ratingsCount: 18000,
    image: 'https://covers.openlibrary.org/b/isbn/9781612680194-L.jpg',
    publishedDate: '1997',
    pageCount: 336,
    publisher: 'Plata Publishing',
    price: 399,
    previewLink: '#',
  },
  {
    id: 'indian-7',
    title: 'Ikigai',
    authors: ['Héctor García'],
    description: 'The Japanese secret to a long and happy life.',
    categories: ['Self-Help'],
    rating: 4.6,
    ratingsCount: 12000,
    image: 'https://covers.openlibrary.org/b/isbn/9780143130727-L.jpg',
    publishedDate: '2017',
    pageCount: 208,
    publisher: 'Penguin Life',
    price: 349,
    previewLink: '#',
  },
  {
    id: 'indian-8',
    title: 'Think Like a Monk',
    authors: ['Jay Shetty'],
    description: 'Timeless wisdom on overcoming negativity and finding purpose.',
    categories: ['Self-Help'],
    rating: 4.7,
    ratingsCount: 7800,
    image: 'https://covers.openlibrary.org/b/isbn/9781982134488-L.jpg',
    publishedDate: '2020',
    pageCount: 352,
    publisher: 'Simon & Schuster',
    price: 499,
    previewLink: '#',
  },
  {
    id: 'indian-9',
    title: 'Sapiens',
    authors: ['Yuval Noah Harari'],
    description: 'A brief history of humankind.',
    categories: ['History'],
    rating: 4.8,
    ratingsCount: 25000,
    image: 'https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg',
    publishedDate: '2011',
    pageCount: 443,
    publisher: 'Harper',
    price: 599,
    previewLink: '#',
  },
  {
    id: 'indian-10',
    title: 'The Palace of Illusions',
    authors: ['Chitra Banerjee Divakaruni'],
    description: 'A reimagining of the world-famous Indian epic, the Mahabharata, told from the point of view of Panchaali.',
    categories: ['Fiction'],
    rating: 4.5,
    ratingsCount: 9200,
    image: 'https://covers.openlibrary.org/b/isbn/9781400077151-L.jpg',
    publishedDate: '2008',
    pageCount: 360,
    publisher: 'Anchor',
    price: 399,
    previewLink: '#',
  },
  {
    id: 'indian-11',
    title: 'The Guide',
    authors: ['R.K. Narayan'],
    description: 'A classic Indian novel about a tour guide who becomes a spiritual guru.',
    categories: ['Literature'],
    rating: 4.4,
    ratingsCount: 4500,
    image: 'https://covers.openlibrary.org/b/isbn/9780143039648-L.jpg',
    publishedDate: '1958',
    pageCount: 220,
    publisher: 'Penguin Classics',
    price: 249,
    previewLink: '#',
  },
  {
    id: 'indian-12',
    title: 'Malgudi Days',
    authors: ['R.K. Narayan'],
    description: 'A collection of short stories set in the fictional town of Malgudi.',
    categories: ['Short Stories'],
    rating: 4.7,
    ratingsCount: 6800,
    image: 'https://covers.openlibrary.org/b/isbn/9780140061352-L.jpg',
    publishedDate: '1943',
    pageCount: 256,
    publisher: 'Penguin Classics',
    price: 299,
    previewLink: '#',
  },
  {
    id: 'indian-13',
    title: 'Trains to Pakistan',
    authors: ['Khushwant Singh'],
    description: 'A powerful novel about the partition of India.',
    categories: ['History'],
    rating: 4.6,
    ratingsCount: 5200,
    image: 'https://covers.openlibrary.org/b/isbn/9780143065883-L.jpg',
    publishedDate: '1956',
    pageCount: 192,
    publisher: 'Penguin India',
    price: 199,
    previewLink: '#',
  },
  {
    id: 'indian-14',
    title: 'The God of Small Things',
    authors: ['Arundhati Roy'],
    description: 'A story about the childhood experiences of fraternal twins whose lives are destroyed by the "Love Laws".',
    categories: ['Fiction'],
    rating: 4.3,
    ratingsCount: 11000,
    image: 'https://covers.openlibrary.org/b/isbn/9780679457312-L.jpg',
    publishedDate: '1997',
    pageCount: 340,
    publisher: 'Random House',
    price: 449,
    previewLink: '#',
  },
  {
    id: 'indian-15',
    title: 'The White Tiger',
    authors: ['Aravind Adiga'],
    description: 'A darkly humorous perspective of India\'s class struggle.',
    categories: ['Fiction'],
    rating: 4.2,
    ratingsCount: 8900,
    image: 'https://covers.openlibrary.org/b/isbn/9781416562597-L.jpg',
    publishedDate: '2008',
    pageCount: 320,
    publisher: 'Free Press',
    price: 349,
    previewLink: '#',
  },
  {
    id: 'indian-16',
    title: 'Secret of the Nagas',
    authors: ['Amish Tripathi'],
    description: 'The second book of the Shiva Trilogy.',
    categories: ['Indian Mythology'],
    rating: 4.5,
    ratingsCount: 7200,
    image: 'https://covers.openlibrary.org/b/isbn/9789381626344-L.jpg',
    publishedDate: '2011',
    pageCount: 396,
    publisher: 'Westland',
    price: 499,
    previewLink: '#',
  },
  {
    id: 'indian-17',
    title: 'The Oath of the Vayuputras',
    authors: ['Amish Tripathi'],
    description: 'The epic conclusion to the Shiva Trilogy.',
    categories: ['Indian Mythology'],
    rating: 4.7,
    ratingsCount: 9500,
    image: 'https://covers.openlibrary.org/b/isbn/9789382618348-L.jpg',
    publishedDate: '2013',
    pageCount: 575,
    publisher: 'Westland',
    price: 599,
    previewLink: '#',
  },
  {
    id: 'indian-18',
    title: 'The 5 AM Club',
    authors: ['Robin Sharma'],
    description: 'Own your morning. Elevate your life.',
    categories: ['Self-Help'],
    rating: 4.4,
    ratingsCount: 15000,
    image: 'https://covers.openlibrary.org/b/isbn/9781443456623-L.jpg',
    publishedDate: '2018',
    pageCount: 336,
    publisher: 'HarperCollins',
    price: 449,
    previewLink: '#',
  },
  {
    id: 'indian-19',
    title: 'Deep Work',
    authors: ['Cal Newport'],
    description: 'Rules for focused success in a distracted world.',
    categories: ['Productivity'],
    rating: 4.7,
    ratingsCount: 18000,
    image: 'https://covers.openlibrary.org/b/isbn/9781455586691-L.jpg',
    publishedDate: '2016',
    pageCount: 304,
    publisher: 'Grand Central Publishing',
    price: 499,
    previewLink: '#',
  },
  {
    id: 'indian-20',
    title: 'The Psychology of Money',
    authors: ['Morgan Housel'],
    description: 'Timeless lessons on wealth, greed, and happiness.',
    categories: ['Finance'],
    rating: 4.8,
    ratingsCount: 22000,
    image: 'https://covers.openlibrary.org/b/isbn/9780857197689-L.jpg',
    publishedDate: '2020',
    pageCount: 252,
    publisher: 'Harriman House',
    price: 399,
    previewLink: '#',
  },
  {
    id: 'indian-21',
    title: 'Can\'t Hurt Me',
    authors: ['David Goggins'],
    description: 'Master your mind and defy the odds.',
    categories: ['Self-Help'],
    rating: 4.9,
    ratingsCount: 30000,
    image: 'https://covers.openlibrary.org/b/isbn/9781544512281-L.jpg',
    publishedDate: '2018',
    pageCount: 364,
    publisher: 'Lioncrest Publishing',
    price: 549,
    previewLink: '#',
  },
  {
    id: 'indian-22',
    title: 'Scion of Ikshvaku',
    authors: ['Amish Tripathi'],
    description: 'The first book of the Ram Chandra series.',
    categories: ['Indian Mythology'],
    rating: 4.4,
    ratingsCount: 6500,
    image: 'https://covers.openlibrary.org/b/isbn/9789385152146-L.jpg',
    publishedDate: '2015',
    pageCount: 354,
    publisher: 'Westland',
    price: 449,
    previewLink: '#',
  },
  {
    id: 'indian-23',
    title: 'Life\'s Amazing Secrets',
    authors: ['Gaur Gopal Das'],
    description: 'How to find balance and purpose in your life.',
    categories: ['Self-Help'],
    rating: 4.6,
    ratingsCount: 8200,
    image: 'https://covers.openlibrary.org/b/isbn/9780143442295-L.jpg',
    publishedDate: '2018',
    pageCount: 256,
    publisher: 'Penguin Ananda',
    price: 299,
    previewLink: '#',
  },
  {
    id: 'indian-24',
    title: 'The monk who sold his ferrari',
    authors: ['Robin Sharma'],
    description: 'A fable about fulfilling your dreams and reaching your destiny.',
    categories: ['Self-Help'],
    rating: 4.5,
    ratingsCount: 14000,
    image: 'https://covers.openlibrary.org/b/isbn/9780062515674-L.jpg',
    publishedDate: '1997',
    pageCount: 198,
    publisher: 'HarperOne',
    price: 249,
    previewLink: '#',
  },
  {
    id: 'indian-25',
    title: 'Man\'s Search for Meaning',
    authors: ['Viktor E. Frankl'],
    description: 'An introduction to logotherapy.',
    categories: ['Psychology'],
    rating: 4.8,
    ratingsCount: 28000,
    image: 'https://covers.openlibrary.org/b/isbn/9780807014295-L.jpg',
    publishedDate: '1946',
    pageCount: 165,
    publisher: 'Beacon Press',
    price: 349,
    previewLink: '#',
  },
  {
    id: 'indian-26',
    title: 'The 4-Hour Workweek',
    authors: ['Timothy Ferriss'],
    description: 'Escape 9-5, live anywhere, and join the new rich.',
    categories: ['Business'],
    rating: 4.3,
    ratingsCount: 12000,
    image: 'https://covers.openlibrary.org/b/isbn/9780307465351-L.jpg',
    publishedDate: '2007',
    pageCount: 308,
    publisher: 'Crown',
    price: 499,
    previewLink: '#',
  },
  {
    id: 'indian-27',
    title: 'Thinking, Fast and Slow',
    authors: ['Daniel Kahneman'],
    description: 'A look at the two systems that drive the way we think.',
    categories: ['Psychology'],
    rating: 4.6,
    ratingsCount: 19000,
    image: 'https://covers.openlibrary.org/b/isbn/9780374275631-L.jpg',
    publishedDate: '2011',
    pageCount: 499,
    publisher: 'Farrar, Straus and Giroux',
    price: 549,
    previewLink: '#',
  },
  {
    id: 'indian-28',
    title: 'Zero to One',
    authors: ['Peter Thiel'],
    description: 'Notes on startups, or how to build the future.',
    categories: ['Business'],
    rating: 4.5,
    ratingsCount: 16000,
    image: 'https://covers.openlibrary.org/b/isbn/9780804139298-L.jpg',
    publishedDate: '2014',
    pageCount: 210,
    publisher: 'Currency',
    price: 449,
    previewLink: '#',
  },
  {
    id: 'indian-29',
    title: 'The Lean Startup',
    authors: ['Eric Ries'],
    description: 'How today\'s entrepreneurs use continuous innovation to create radically successful businesses.',
    categories: ['Business'],
    rating: 4.4,
    ratingsCount: 15000,
    image: 'https://covers.openlibrary.org/b/isbn/9780307887894-L.jpg',
    publishedDate: '2011',
    pageCount: 336,
    publisher: 'Crown Business',
    price: 499,
    previewLink: '#',
  },
  {
    id: 'indian-30',
    title: 'Start with Why',
    authors: ['Simon Sinek'],
    description: 'How great leaders inspire everyone to take action.',
    categories: ['Leadership'],
    rating: 4.6,
    ratingsCount: 13000,
    image: 'https://covers.openlibrary.org/b/isbn/9781591842804-L.jpg',
    publishedDate: '2009',
    pageCount: 256,
    publisher: 'Portfolio',
    price: 449,
    previewLink: '#',
  },
];

export const CATEGORIES = [
  'Fiction',
  'Self-Help',
  'History',
  'Indian Mythology',
  'Business',
  'Psychology',
  'Finance',
  'Biography',
  'Literature',
  'Science',
];
